const typeDefs = `
  type User {
    _id: ID
    username: String
    email: String
    password: String
    jobStatus: String
    linkedin: String
    gitHub: String
  projects: [Project]!
  }

  type Project {
    _id: ID
    description: String
    title: String
    githubRepo: String
    contactInfo: String
    createdAt: String
    projectAuthor: String
    comments: [Comment]!
  }
  type Resources {
    _id: ID
    topic: String
    content: String  
    createdAt: String
  }

  type Comment {
    _id: ID
    commentText: String
    commentAuthor: String
    createdAt: String
 }

  type Auth {
    token: ID!
    user: User
  }

  type Query {
    users: [User]
    user(username: String): User
    projects(username: String): [Project]
    project(projectId: ID!): Project
    resources(username:String, topic: String):[Resources]
    me: User
  }

  type Mutation {
    addUser(username: String!, email: String!, password: String!): Auth
    login(email: String!, password: String!): Auth
    addProject(description: String!, title: String!, githubRepo: String!, contactInfo:String! ): Project
    addResource(topic: String!, content: String!):Resources
    addComment(projectId: ID!, commentText: String!): Project
    removeProject(projectId: ID!): Project
    removeResource(resourcesId: ID!): Resources
    removeComment(projectId: ID!, commentId: ID!): Project
  }
`;

module.exports = typeDefs;
